### ISSUE TITLE
COVID-19

### ISSUE THREAD

**Issue by ian-r-rose** [CityOfLosAngeles/public-health-prototype#31]
Show some stats, here and in an AGOL map.

Relevant links:
[LA County public health release](http://publichealth.lacounty.gov/phcommon/public/media/mediapubhpdetail.cfm?prid=2249)
[Johns Hopkins AGOL map](https://www.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6), [blog post](https://systems.jhu.edu/research/public-health/ncov/), [feature layer](https://www.arcgis.com/home/webmap/viewer.html?layers=c0b356e20b30490c8b8b4c7bb9554e7c)
[CDC Cases in the US](https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html)

**Comment by JeanneHolm** [comment]
Other sources from the CDC [are noted here](https://www.cdc.gov/coronavirus/2019-ncov/locations-confirmed-cases.html).

These [underlying situation reports ](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/situation-reports/) are helpful, but are being published in PDF.  The data dictionary behind [these is here](https://www.who.int/publications-detail/global-surveillance-for-human-infection-with-novel-coronavirus-(2019-ncov) ).

[COVID cases in the US are shown here](https://www.cdc.gov/coronavirus/2019-ncov/cases-in-us.html  ).

**Comment by tiffanychu90** [comment]
ArcGIS Online Dashboard, fully public link: https://lahub.maps.arcgis.com/apps/opsdashboard/index.html#/82b3434c38ac4fad80cc281efbeb96ca

**Comment by hunterowens** [comment]
closed via #33
