### ISSUE TITLE
Add bayes model projections with WIDE error bars to Timeseries dashboard

### ISSUE THREAD

**Issue by hunterowens** [CityOfLosAngeles/public-health-prototype#35]

**Comment by hunterowens** [comment]
^ @ian-r-rose @tiffanychu90 @hunterowens had a chat 4->4:30 

@ian-r-rose to port ML model to Los Angeles time series 

@tiffanychu90 to compile list of scenarios/ models

**Comment by hunterowens** [comment]
[Harvard / Propublica Scenario / Models](https://globalepidemics.org/2020/03/17/caring-for-covid-19-patients/)

**Comment by tiffanychu90** [comment]
London School of Hygiene and Tropical Medicine’s mathematical modeling...can we adapt this? It seems way more complicated. But TLDR, HK changed their R0 (reproduction number) when intervening.
https://cmmid.github.io/topics/covid19/current-patterns-transmission/global-time-varying-transmission.html

**Comment by hunterowens** [comment]
done!
