### ISSUE TITLE
mirroring data in Civis 

### ISSUE THREAD

**Issue by sherryshenker** [CityOfLosAngeles/public-health-prototype#44]
Starting an issue to discuss how we can transfer data to Civis in order to set up a v1 of the app in Platform (separate from any changes to ETL).

Looking at the code, it looks like the main thing we need is the postgres connection [here](https://github.com/CityOfLosAngeles/public-health-prototype/blob/a443561dc1acf074fe7ab505b97b9328981a2008/dashboard/load_data.R#L20) @hunterowens

**Comment by hunterowens** [comment]
Yep. I've opened a ticket to have the IP whitelisted and have the PEM now. I will attempt to setup a connection on Monday

**Comment by hunterowens** [comment]
close incomplete
